# -*- coding: utf-8 -*-
"""1PY20abril.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lOu4CXApbJA6GbAZ6DOrAMHB6HJWaWv2

# Curso de progamaçao em python
"""

print("olá SENAI") # meu primeiro codigo

Print('oi vida') #meu primeiro erro

Print("erro de sintaxe!)

print('erro'

"""# Trabalhando com dados literais"""

print(12375.8) # primeiro numero fracionario- float

print(12.378,9)

print('luiz','kassia', sep='********')

print(12375.08) # "." é a separaçao de decimais

"""Booleano"""

5 > 2# dado booleano

"""# operaçoes em python"""

# @title Adição

print(8 + 10)    # Exemplo de Adição

print(56 + 9.4) # Exemplo de adiçao e float

# @title Subtraçao

print(345 - 78) # exemplo de subtraçao

print( 1.45 - 27) #subtraçao entre inteiro e float

# @title multiplicação

print(3*3) #exemplo de multiplicaçao

print(4.5 * 18) #exemplo de multiplicaçao de float

# @title divisão

print(100/5) # exemplo de divisão (todo resultado será float)

print( 100 // 5 ) #exemplo de divisão inteira (nao será float, divisão inteira)

print(100 // 5.0) #exemplo de divisão inteira com float

# @title Exponenciação

print(2 ** 3) #exemplo de exponenciação

print(4.8**4) #exemplo de exponenciação

# @title Módulo

print(12%5)  #exemplo de modulo(mostra o resto de uma divisão)

print(12%4.5) #exemplo de modulo entre

"""# Exercicio 1

Crie um progama para receber dois valores e em seguida exiba soma desses valores
"""

# Progama para receber dois valores e exibir a soma

valor1=550  #primeira variavel
valor2=218  #segunda variavel

soma = (valor1+valor2) #exemplo de operação

print('O resultado de valor 1 e valor 2 é ',soma)

fabrri =5
legal =2

booleano = 5>2

print('fabbri é legal?,', booleano)

"""# Exercicio 2"""

# Progama para receber dois valores e exibir a subtração

valor1=550  #primeira variavel
valor2=218  #segunda variavel

sub = (valor1-valor2) #exemplo de operação

print('O resultado de valor 1 e valor 2 é ',sub)

"""# Exercicio 3"""

# Progama para receber dois valores e exibir a multiplicação

valor1=550  #primeira variavel
valor2=218  #segunda variavel

mul = (valor1-valor2) #exemplo de operação

print('O resultado de valor 1 e valor 2 é ',mul)

"""# Exercicio 4"""

# progama para receber dois valores e exibir a divisão

valor1= 20 #primeiro valor

valor2= 2  #segundo valor

divi= (valor1/valor2)

print("o resultado de valor1 e valor2" ,divi)

"""# Exercicio 5"""

# progama para receber dois valores e exibir o resto da divisão

valor= 12
valor2= 7

res = (valor1%valor2)

print( 'O resto da divisao do valor1 e valor2', res)

"""# Exercicio 6"""

# progama para receber um valor ao quadrado de um numero

valor= 40
valor2

pot= (valor1**valor2)

print('o valor da potencia dos valores é', pot)

"""# Exercicio 7"""

# progama para receber um valor sobre a raiz quadrada

valor1= 121
ra= (valor1** (1/2))

print('O valor da raiz do valor1 é',ra)

res1=('ele é um otimo professor')

res2=('ele é muito engraçado')

proba=100/2

# Exemplo de biblioteca math

import math # importar a biblioteca

#numero=45 # criando a variavel

numero= float(input('digite um numero'))

raizquadrada= math.sqrt(numero)
print('a raiz quadrada é', raizquadrada)

"""exercicico de 4 numeros"""

from ast import Yield
# Progama dos 4 numeros

print('inicio de progama')
# Entrada progama
A= float(input('digite o primeiro numero...\n'))
B= float(input('digite o segundo numero:'))
C= float(input('digite o terçeiro numero:'))
D= float(input('digite o quarto numero:'))

# Processamento

X= A * B
Y= C * D

Resultado = X - Y

print('O resultado de X - Y é' , Resultado)

print('\nFim do progama...')

"""# Ordem dos operdadores"""

# exemplo de operação modulo

print(9%6&2) # esse operador tem ligação pelo lado esquerdo
# executar da esquerda para direita

# exemplo de operçao exponenciação

print(2**2**3) # esse operdador tem ligação pelo lado direito
# executar da direita para esquerda

"""# Indetificando o tipo de dados

teste defina o tipo de dados de:

4, 307, 187789.7 'Noel' "-307', SENAI
"""

# Exemplo de teste de tipo de dados

print('4, é considerado')
print(type(4))
print('\n307 é considerado')

print('\n187789.7 é considerado')

print('\n "Noel" é considerado')

print('\n"-307\' é considerado')
print('\nSENAI é considerado')

"""# texto e seus segredos"""

# @title descobrindo quantas letras há em uma palavra

palavra= 'o rato roeu a roupa do rei de roma'

len(palavra)

"""Descubra quantas letras tem em:

'cadeias de caracteres'

'joão tem 22 anos e R$78,98 no bolso'
''
"""

palavra1= 'cadeia de caracteres'

palavra2= 'joão tem 22 anos e R$78,98 no bolso'

palavra3= ''

len(palavra1)
len(palavra2)
len(palavra3)

print(2*5)