# -*- coding: utf-8 -*-
"""25deMaio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GmHJWzYrfQdAg-uBWgblFQEwL2rECHtg

# Progamação orientada a objeto em Python
"""

# @title Um exemplo pratico de criação de classe

class Pessoa:
    def __init__(self, nome:str,idade:int,altura:float):
        self.nome = nome
        self.idade = idade
        self.altura = altura

    def dizer_ola(self):
        print(f'ola, meu nome é {self.nome}\n')
        print(f'Tenho {self.idade} anos de idade')
        print(f'E minha altura é {self.altura}')

    def cozinhar(self, receita:str):
        print(f'Estou cozinhando um(a) {receita}')

    def andar(self, distancia:float):
        print(f'Sai para andar, Volto depois de completar {distancia} metros...')

# Criar uma instancia da classe pessoa

um_mano = Pessoa(nome='Rafael', idade=20, altura=1.80)

# Invocando uma classe de pessoa

um_mano.dizer_ola()
um_mano.cozinhar('Red Velvet')
um_mano.andar(5000)

youtuber = Pessoa(nome='A lenda', idade=40, altura=1.70)

youtuber.dizer_ola()

# @title Outro exemplo de código que cria uma classe

class Televisao():  #Criando uma classe
    def __init__(self): # um metodo especial chamado constr
        self.ligada= False # Um atributo do objeto
        self.canal= 2 # Um outro atributo do objeto

# @title Exemplo de criação de uma instancia

smart = Televisao()

smart.ligada

smart.canal

tvdasla = Televisao()

# @title Exmeplo de alteração de valor e atributo

tvdasla.ligada = True

tvdasla.ligada
tvdasla.canal=4

tvdasla.canal

print(f'O canal da smart é o {smart.canal}')
print(f'O canal da tv da sala é {tvdasla.canal}')

# @title Associar um novo comportamento

class Televisao():
    def __init__(self):
       self.ligada=False
       self.canal=2

    def muda_canal_para_baixo(self):
        self.canal -= 1

    def muda_canal_para_cima(self):
        self.canal += 1

novatv = Televisao()



print(f'Antes de mudar de canal, nova tv estava no canal {novatv.canal}')

novatv.muda_canal_para_cima()

print(f'Depois de mudar de canal, a nova tv está no canal {novatv.canal}')

print(f'Antes de mudar de canal, a nova tv estava no canal {novatv.canal}')

novatv.muda_canal_para_baixo()

print(f'Depois de mudar de canal a nova tv esta no canal {novatv.canal}')

# @title modificar um construtor


class Televisao():
    def __init__(self, min, max):
       self.ligada=False
       self.canal=2
       self.cmin = min
       self.cmax = max

    def muda_canal_para_baixo(self):
        if self.canal -1 >= self.cmin:
            self.canal -= 1
            print('canal alterado')
        else:
            print('Não pode acessar essa faxa de canais')


    def muda_canal_para_cima(self):
        if self.canal + 1 <= self.cmax:
            self.canal += 1
            print('Canal alterado')
        else:
            print('Não pode acessar essa faxa de canais')

tvdacopa = Televisao(0, 15)

novatv.muda_canal_para_baixo()

novatv.canal

for c in range(18):
    tvdacopa.muda_canal_para_cima()

import pygame

help(pygame)

